#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG base_img
FROM $base_img
WORKDIR /

USER 0

RUN mkdir ${SPARK_HOME}/python
RUN apt-get update && \
    apt-get install -y curl git zlib1g-dev libssl-dev libreadline-dev gcc make && \
    ln -s /home/spark/.pyenv/versions/3.6.9/bin/python3 /usr/bin/python && \
    ln -s /home/spark/.pyenv/versions/3.6.9/bin/python3 /usr/bin/python3 && \
    apt install -y python python-pip && \
    rm -rf /var/cache/apt/*

COPY python/lib ${SPARK_HOME}/python/lib
ENV PYTHONPATH ${SPARK_HOME}/python/lib/pyspark.zip:${SPARK_HOME}/python/lib/py4j-*.zip

WORKDIR /opt/spark/work-dir
ENTRYPOINT [ "/opt/entrypoint.sh" ]

ARG spark_uid=185
USER ${spark_uid}

RUN cd /home/spark/ && \
    curl https://pyenv.run | bash && \
    /home/spark/.pyenv/bin/pyenv install 3.6.9 && \
    /home/spark/.pyenv/bin/pyenv install 3.7.7 && \
    /home/spark/.pyenv/bin/pyenv install 3.8.1 && \
    /home/spark/.pyenv/bin/pyenv global 3.6.9 && \
    rm -rf /tmp/python-build*
